[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
filter_files = true
force_single_line = true
line_length = 120
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=model_manipulation_software --cov-report term-missing --strict-markers"
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"'"]

[tool.coverage.run]
omit = [
	"*/__version__.py"
]
